services:
  bookstore:
    image: bookstore-api:1.0.0
    build:
      dockerfile: Dockerfile-app
    container_name: bookstore-api
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - mongo-db-network
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - mongo-database:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - mongo-db-network

  # Interface web para o mongo
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-interface
    restart: unless-stopped
    ports:
      - 27018:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
      ME_CONFIG_MONGODB_PORT: ${MONGODB_PORT}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
    links:
      - mongodb
    depends_on:
      - mongodb
    networks:
      - mongo-db-network

networks:
  mongo-db-network:

volumes:
  mongo-database: