services:
  bookstore:
    image: bookstore-api:1.0.0
    build:
      dockerfile: Dockerfile-app
    container_name: bookstore-api
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - bookstore-network

networks:
  bookstore-network:

volumes:
  bookstore-database: